language: node_js
node_js: stable
install:
  - npm install
  - npm install -g codecov
script: npm run test:ci
after_success:
  - codecov --file test/coverage/lcov.info --disable search
notifications:
  email: false
